### PR TITLE
Space app

### PR DESCRIPTION
**Pull request by haythemsellami**

### CODE REVIEW

**Comment by bumi** [comment]
do we need all those shared test-helpers or can those be loaded externally from some package?

**Comment by haythemsellami** [comment]
the shared folder is basically the same as @aragon/test-helpers package, but I had a problem with that package so I used that shared folder from [planning-suite project](https://github.com/AutarkLabs/planning-suite) .... in that shared folder we can remove the contracts folder...

**Comment by bumi** [comment]
do we need all of `shared/test-helpers` ? or can they be some external dependency?

**Comment by haythemsellami** [comment]
need to remove unnecessary files

**Pull request closed without merging**
