### PR TITLE
fix apps apm namehash

### PR DESCRIPTION
**Pull request by haythemsellami**

### CODE REVIEW

**Comment by bumi** [comment]
So does this still work locally? because locally the apm `aragonpm.eth` is used, isn't it?

**Comment by haythemsellami** [comment]
mmm no it does not work

**Comment by bumi** [comment]
maybe we should pass it in from JavaScript? I think that is how it is done in the kredits deploy script?

**Comment by bumi** [comment]
btw. there is also this related aragon issue: https://github.com/aragon/aragen/issues/10

**Pull request merged**
